default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_hangman_development

test:
  <<: *default
  database: rails_hangman_test

production:
  <<: *default
  database: rails_hangman_production
  username:
  password:
