require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe HangmanGamesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # HangmanGame. As you add validations to HangmanGame, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HangmanGamesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all hangman_games as @hangman_games" do
      hangman_game = HangmanGame.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:hangman_games)).to eq([hangman_game])
    end
  end

  describe "GET #show" do
    it "assigns the requested hangman_game as @hangman_game" do
      hangman_game = HangmanGame.create! valid_attributes
      get :show, {:id => hangman_game.to_param}, valid_session
      expect(assigns(:hangman_game)).to eq(hangman_game)
    end
  end

  describe "GET #new" do
    it "assigns a new hangman_game as @hangman_game" do
      get :new, {}, valid_session
      expect(assigns(:hangman_game)).to be_a_new(HangmanGame)
    end
  end

  describe "GET #edit" do
    it "assigns the requested hangman_game as @hangman_game" do
      hangman_game = HangmanGame.create! valid_attributes
      get :edit, {:id => hangman_game.to_param}, valid_session
      expect(assigns(:hangman_game)).to eq(hangman_game)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new HangmanGame" do
        expect {
          post :create, {:hangman_game => valid_attributes}, valid_session
        }.to change(HangmanGame, :count).by(1)
      end

      it "assigns a newly created hangman_game as @hangman_game" do
        post :create, {:hangman_game => valid_attributes}, valid_session
        expect(assigns(:hangman_game)).to be_a(HangmanGame)
        expect(assigns(:hangman_game)).to be_persisted
      end

      it "redirects to the created hangman_game" do
        post :create, {:hangman_game => valid_attributes}, valid_session
        expect(response).to redirect_to(HangmanGame.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved hangman_game as @hangman_game" do
        post :create, {:hangman_game => invalid_attributes}, valid_session
        expect(assigns(:hangman_game)).to be_a_new(HangmanGame)
      end

      it "re-renders the 'new' template" do
        post :create, {:hangman_game => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hangman_game" do
        hangman_game = HangmanGame.create! valid_attributes
        put :update, {:id => hangman_game.to_param, :hangman_game => new_attributes}, valid_session
        hangman_game.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested hangman_game as @hangman_game" do
        hangman_game = HangmanGame.create! valid_attributes
        put :update, {:id => hangman_game.to_param, :hangman_game => valid_attributes}, valid_session
        expect(assigns(:hangman_game)).to eq(hangman_game)
      end

      it "redirects to the hangman_game" do
        hangman_game = HangmanGame.create! valid_attributes
        put :update, {:id => hangman_game.to_param, :hangman_game => valid_attributes}, valid_session
        expect(response).to redirect_to(hangman_game)
      end
    end

    context "with invalid params" do
      it "assigns the hangman_game as @hangman_game" do
        hangman_game = HangmanGame.create! valid_attributes
        put :update, {:id => hangman_game.to_param, :hangman_game => invalid_attributes}, valid_session
        expect(assigns(:hangman_game)).to eq(hangman_game)
      end

      it "re-renders the 'edit' template" do
        hangman_game = HangmanGame.create! valid_attributes
        put :update, {:id => hangman_game.to_param, :hangman_game => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested hangman_game" do
      hangman_game = HangmanGame.create! valid_attributes
      expect {
        delete :destroy, {:id => hangman_game.to_param}, valid_session
      }.to change(HangmanGame, :count).by(-1)
    end

    it "redirects to the hangman_games list" do
      hangman_game = HangmanGame.create! valid_attributes
      delete :destroy, {:id => hangman_game.to_param}, valid_session
      expect(response).to redirect_to(hangman_games_url)
    end
  end

end
